URL_BASE = "http://localhost:4723"
PLATFORM_NAME = "Android"
PLATFORM_VERSION = "11"
DEVICE_NAME = "Pixel4Android11"
AUTOMATION_NAME = "UiAutomator2"
APP =  "/app/product_registration.apk"
UDID = "emulator-5554"